# Generated by Django 4.1.4 on 2023-08-28 11:50

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_set', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=150)),
                ('title_description', models.TextField()),
                ('title_image', models.ImageField(blank=True, null=True, upload_to='about_images/', verbose_name='Image (470*450)')),
                ('sub_title', models.CharField(max_length=150)),
                ('sub_text', models.TextField()),
                ('why_us', models.TextField()),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('goal', models.TextField()),
            ],
            options={
                'verbose_name_plural': '03.About Page Content',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('blog', models.TextField()),
                ('image', models.ImageField(upload_to='blogs_images/', verbose_name='Blog Image (370*270)')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '06. Blogs',
            },
        ),
        migrations.CreateModel(
            name='CompanySetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_set', models.CharField(max_length=200)),
                ('color_logo', models.ImageField(upload_to='logos', verbose_name='Color Logo (170*55)')),
                ('white_logo', models.ImageField(upload_to='logos', verbose_name='White Logo (170*55)')),
                ('company_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('opening_hours', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('privacy_policy', models.TextField()),
                ('terms_and_conditions', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '01. Company Setup',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('contact', models.TextField()),
                ('subject', models.TextField(blank=True, null=True)),
                ('message', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '05. Contact',
            },
        ),
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_set', models.CharField(max_length=200)),
                ('header_heading', models.CharField(max_length=150)),
                ('header_text', models.TextField()),
                ('header_image', models.ImageField(upload_to='home_images/', verbose_name='Header Image (585*335)')),
                ('header_button_text', models.CharField(max_length=100)),
                ('header_button_url', models.URLField()),
                ('service_title', models.CharField(max_length=255)),
                ('bottom_title', models.CharField(max_length=150)),
                ('bottom_sub_title', models.CharField(max_length=150)),
                ('bottom_text', models.TextField()),
                ('bottom_image', models.ImageField(upload_to='home_images/', verbose_name='Bottom Image (570*465)')),
                ('years_of_experience', models.IntegerField()),
                ('countries', models.FloatField()),
                ('employees', models.IntegerField()),
                ('clients', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': '02.Home Page Content',
            },
        ),
        migrations.CreateModel(
            name='JobVacancyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '09. Vacancy Category',
            },
        ),
        migrations.CreateModel(
            name='JobVacancyInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('vacancy', models.CharField(max_length=255)),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '11. Demand Inquiry',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=200)),
                ('service_description', models.TextField()),
                ('service_image', models.ImageField(upload_to='Services_images/', verbose_name='Service Image (370*250)')),
                ('order', models.IntegerField(default=0)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='service_title', unique=True)),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '07. Services',
            },
        ),
        migrations.CreateModel(
            name='ServiceInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('service', models.CharField(max_length=255)),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '08. Service Inquiry',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider_images', verbose_name='Image (1920*800)')),
                ('heading_text', models.CharField(max_length=200)),
                ('sub_heading_text', models.CharField(max_length=200)),
                ('button_text', models.CharField(max_length=50)),
                ('button_url', models.URLField()),
            ],
            options={
                'verbose_name_plural': '04. Slider',
            },
        ),
        migrations.CreateModel(
            name='JobVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('both', 'both')], max_length=255)),
                ('openings', models.IntegerField()),
                ('job_description', models.TextField()),
                ('job_image', models.ImageField(upload_to='job_images/', verbose_name='Featured Image (270*170)')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='job_title', unique=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='features.jobvacancycategory')),
            ],
            options={
                'verbose_name_plural': '10. Vacancy ',
            },
        ),
    ]
