# Generated by Django 4.1.4 on 2023-08-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
