# Generated by Django 4.1.4 on 2023-08-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='cliensats',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
