# Generated by Django 4.1.4 on 2023-08-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_alter_service_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysetup',
            name='secondary_contact',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companysetup',
            name='secondary_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
