# Generated by Django 4.1.4 on 2023-08-09 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_homecontent_cliensats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecontent',
            name='cliensats',
        ),
    ]
