# Generated by Django 4.1.4 on 2023-08-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_companysetup_secondary_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=255, verbose_name='Service title.')),
                ('service_description', models.TextField()),
            ],
            options={
                'verbose_name_plural': '13. Services',
            },
        ),
        migrations.CreateModel(
            name='ServicePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_set', models.CharField(default='Click to Edit', max_length=255)),
                ('service_title', models.TextField()),
                ('why_chose_us', models.TextField()),
                ('get_started', models.TextField()),
            ],
            options={
                'verbose_name_plural': '12. Service Page Content',
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': '07. Sectors'},
        ),
    ]
