# Generated by Django 4.1.4 on 2023-08-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_companyservice_servicepagecontent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyservice',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
