# Generated by Django 4.1.4 on 2023-08-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0007_serviceinquiry_alter_service_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_set', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=150)),
                ('title_description', models.TextField()),
                ('title_image', models.ImageField(blank=True, null=True, upload_to='about_images/')),
                ('sub_title', models.CharField(max_length=150)),
                ('sub_text', models.TextField()),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('goal', models.TextField()),
                ('market_depth', models.TextField()),
            ],
            options={
                'verbose_name_plural': '11.About Page Content',
            },
        ),
        migrations.DeleteModel(
            name='AboutContent',
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': '05. Blogs'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': '04. Contact'},
        ),
        migrations.AlterModelOptions(
            name='serviceinquiry',
            options={'verbose_name_plural': '07. Service Inquiry'},
        ),
    ]
