# Generated by Django 4.1.4 on 2023-08-15 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0008_aboutpagecontent_delete_aboutcontent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpagecontent',
            name='market_depth',
        ),
    ]
