# Generated by Django 4.1.4 on 2023-08-15 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0009_remove_aboutpagecontent_market_depth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faqs',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
