# Generated by Django 4.1.4 on 2023-08-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0010_delete_faqs_delete_team_delete_teammember_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpagecontent',
            options={'verbose_name_plural': '03.About Page Content'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': '06. Blogs'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': '05. Contact'},
        ),
        migrations.AlterModelOptions(
            name='homecontent',
            options={'verbose_name_plural': '02.Home Page Content'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': '07. Services'},
        ),
        migrations.AlterModelOptions(
            name='serviceinquiry',
            options={'verbose_name_plural': '08. Service Inquiry'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': '04. Slider'},
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='why_us',
            field=models.TextField(default='sdasdasd'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='title_image',
            field=models.ImageField(blank=True, null=True, upload_to='about_images/', verbose_name='Image (470*450)'),
        ),
    ]
