# Generated by Django 4.1.4 on 2023-08-28 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0011_alter_aboutpagecontent_options_alter_blog_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecontent',
            name='service_text',
        ),
    ]
