# Generated by Django 4.1.4 on 2023-08-18 09:16

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0012_vacancy_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name_plural': '10. Vacancy '},
        ),
        migrations.AlterModelOptions(
            name='vacancycategory',
            options={'verbose_name_plural': '09. Vacancy Category'},
        ),
        migrations.AddField(
            model_name='vacancy',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='sdad', editable=False, populate_from='job_title', unique=True),
            preserve_default=False,
        ),
    ]
