# Generated by Django 4.1.4 on 2023-08-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0013_alter_vacancy_options_alter_vacancycategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='job_image',
            field=models.ImageField(default='dasd', upload_to='job_images/', verbose_name='Featured Image (270*170)'),
            preserve_default=False,
        ),
    ]
