# Generated by Django 4.1.4 on 2023-08-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0014_vacancy_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
