# Generated by Django 4.1.4 on 2023-08-18 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0016_vacancyinquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancyinquiry',
            old_name='demand',
            new_name='vacancy',
        ),
    ]
